name: research_geo_env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy=1.25.2
  - pandas
  - geopandas
  - pyogrio
  - fiona
  - shapely
  - gdal
  - matplotlib
  - seaborn
  - jupyter
  - notebook
  - ipykernel
  - ipywidgets
  - contextily
  - pyproj
  - rich
  - scikit-learn
  - folium
  - pip
  - pip:
      - streamlit
      - streamlit-folium
      - streamlit-geopandas
      - strait
      - git-lfs
